# Generated by Django 5.2.7 on 2026-04-14 18:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvz_name', models.CharField(max_length=100)),
                ('pvz_work_schedule', models.CharField(max_length=100)),
                ('pvz_contact_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('worked_hours', models.IntegerField(default=0, verbose_name='Отработано часов')),
                ('late_count', models.IntegerField(default=0, verbose_name='Количество опозданий')),
                ('overtime_count', models.IntegerField(default=0, verbose_name='Количество переработок')),
                ('role', models.CharField(choices=[('employee', 'Сотрудник'), ('manager', 'Управляющий'), ('admin', 'Администратор')], default='employee', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('pvz', models.ManyToManyField(blank=True, related_name='users', to='schedule_app.pvz')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanliness', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Чистота')),
                ('service_speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Скорость обслуживания')),
                ('politeness', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Вежливость')),
                ('competence', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Компетентность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Оценка сотрудника',
                'verbose_name_plural': 'Оценки сотрудников',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Время входа')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('success', models.BooleanField(default=True, verbose_name='Успешный вход')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита входа',
                'verbose_name_plural': 'Журнал аудита входов',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(verbose_name='Дата заказа')),
                ('order_time', models.TimeField(verbose_name='Время заказа')),
                ('order_number', models.CharField(max_length=50, verbose_name='Номер заказа')),
                ('client_id', models.CharField(max_length=50, verbose_name='ID клиента')),
                ('tracking_number', models.CharField(max_length=100, verbose_name='Трек номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('pvz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.pvz', verbose_name='ПВЗ')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('schedule_change', 'Изменение графика'), ('system', 'Системное уведомление'), ('feedback', 'Новый отзыв'), ('rating', 'Новая оценка')], max_length=20, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('related_pvz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule_app.pvz', verbose_name='Связанный ПВЗ')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, verbose_name='Номер заказа')),
                ('client_id', models.CharField(max_length=50, verbose_name='ID клиента')),
                ('issue_time', models.TimeField(verbose_name='Время выдачи')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('pvz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.pvz', verbose_name='ПВЗ')),
            ],
            options={
                'verbose_name': 'Сгенерированный заказ',
                'verbose_name_plural': 'Сгенерированные заказы',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=50, verbose_name='ID клиента')),
                ('service_speed', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Скорость обслуживания в ПВЗ')),
                ('employee_politeness', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Вежливость сотрудника ПВЗ')),
                ('employee_competence', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Компетентность сотрудника ПВЗ')),
                ('cleanliness', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Чистота ПВЗ')),
                ('convenient_location', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Удобное расположение ПВЗ')),
                ('feedback_text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('pvz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.pvz', verbose_name='ПВЗ')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('shift_type', models.CharField(choices=[('full', 'Полная смена'), ('half', 'Половина смены'), ('day_off', 'Выходной')], max_length=20)),
                ('pvz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.pvz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryOrderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range_start', models.DateField(verbose_name='Начало периода')),
                ('date_range_end', models.DateField(verbose_name='Конец периода')),
                ('generated_data', models.JSONField(verbose_name='Сгенерированные данные')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Путь к файлу')),
                ('preview_data', models.TextField(blank=True, verbose_name='Предпросмотр данных')),
                ('status', models.CharField(choices=[('generated', 'Сгенерировано'), ('approved', 'Подтверждено'), ('imported', 'Импортировано'), ('rejected', 'Отклонено')], default='generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pvz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.pvz', verbose_name='ПВЗ')),
            ],
            options={
                'verbose_name': 'Временные данные заказов',
                'verbose_name_plural': 'Временные данные заказов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(verbose_name='Дата заказов')),
                ('hour_9', models.IntegerField(default=0, verbose_name='09:00-10:00')),
                ('hour_10', models.IntegerField(default=0, verbose_name='10:00-11:00')),
                ('hour_11', models.IntegerField(default=0, verbose_name='11:00-12:00')),
                ('hour_12', models.IntegerField(default=0, verbose_name='12:00-13:00')),
                ('hour_13', models.IntegerField(default=0, verbose_name='13:00-14:00')),
                ('hour_14', models.IntegerField(default=0, verbose_name='14:00-15:00')),
                ('hour_15', models.IntegerField(default=0, verbose_name='15:00-16:00')),
                ('hour_16', models.IntegerField(default=0, verbose_name='16:00-17:00')),
                ('hour_17', models.IntegerField(default=0, verbose_name='17:00-18:00')),
                ('hour_18', models.IntegerField(default=0, verbose_name='18:00-19:00')),
                ('hour_19', models.IntegerField(default=0, verbose_name='19:00-20:00')),
                ('hour_20', models.IntegerField(default=0, verbose_name='20:00-21:00')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('pvz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.pvz', verbose_name='ПВЗ')),
            ],
            options={
                'unique_together': {('pvz', 'order_date')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнена')),
                ('is_global', models.BooleanField(default=False, verbose_name='Общая задача на ПВЗ')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Назначена сотруднику')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('pvz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='schedule_app.pvz', verbose_name='ПВЗ')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pvz', 'status'], name='schedule_ap_pvz_id_5553ef_idx'), models.Index(fields=['assigned_to', 'status'], name='schedule_ap_assigne_1bcf3f_idx'), models.Index(fields=['deadline'], name='schedule_ap_deadlin_a3b837_idx')],
            },
        ),
    ]
